name: Generate TMD Earthquake GeoJSON File

on:
  schedule:
    - cron: '*/5 * * * *'  # สั่งให้บอตตื่นมาแปลงข้อมูลทุกๆ 5 นาที
  workflow_dispatch:      # สร้างปุ่มสำหรับกดรันเพื่อทดสอบด้วยมือตนเองได้

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python Libraries
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas geopandas shapely

    - name: Execute Script
      run: python update_earthquake.py

    - name: Push GeoJSON Back to Repository
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add earthquake_latest.geojson
        git commit -m "Automated update earthquake GeoJSON data" || echo "No changes to commit"
        git push
